const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const express=require('express'),jwt=require('jsonwebtoken'),https=require('node:https'),{EventEmitter}=require('node:events'),{PGlite}=require('@electric-sql/pglite');
test('anonymous seven-day create/send/export, Save-only account gate, expiry, identity and funnel',async(t)=>{
 process.env.JWT_SECRET='anonymous-test-only';process.env.BREVO_API_KEY='stub';delete process.env.GA_API_SECRET;
 const sent=[];let failEmail=false;const original=https.request;
 https.request=(options,cb)=>{const req=new EventEmitter();let body='';req.write=b=>body+=b;req.end=()=>{const res=new EventEmitter();res.statusCode=failEmail?503:201;cb(res);if(!failEmail)sent.push(JSON.parse(body));queueMicrotask(()=>res.emit('end'));};return req;};
 t.after(()=>https.request=original);
 const db=new PGlite();await db.exec(fs.readFileSync('schema.sql','utf8'));
 let queue=Promise.resolve();const pool={query:db.query.bind(db),connect:async()=>{const prev=queue;let release;queue=new Promise(r=>release=r);await prev;return{query:db.query.bind(db),release};}};
 const app=express();app.use(express.json());app.locals.pool=pool;
 for(const route of ['guest','auth','quotes','events','admin'])app.use('/api/'+route,require('../routes/'+route));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{await new Promise(r=>server.close(r));await db.close();});
 const base='http://127.0.0.1:'+server.address().port;
 const call=(url,body,token,method='POST',cookie)=>fetch(base+'/api/'+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const start=await call('guest/start',{browser_id:'fresh-anonymous-browser'});assert.equal(start.status,200);
 const cookie=start.headers.get('set-cookie').split(';')[0],guest=(await start.json()).token;
 const before=await(await call('auth/me',null,guest,'GET')).json();assert.equal(before.trial_active,true);assert.equal(before.quotes_remaining,null);
 assert.equal((await db.query('SELECT * FROM users')).rows.length,0);
 const quote={creation_key:crypto.randomUUID(),customer_name:'Test Customer',customer_email:'test@example.invalid',job_description:'Fit sockets',total:1234,quote_data:{customer_email:'test@example.invalid',labour:900,mats:334,total:1234}};
 let output;
 for(let i=0;i<13;i++){const response=await call('quotes/preview',quote,guest);assert.equal(response.status,200);output=await response.json();}
 assert.equal((await db.query('SELECT * FROM quotes')).rows.length,0,'generation creates no saved quote');
 assert.equal((await call('quotes',quote,guest)).status,403);
 assert.deepEqual(await(await call('quotes',null,guest,'GET')).json(),[]);
 assert.equal((await call('quotes/send-email',{...quote},guest)).status,400,'raw data cannot bypass signed output');
 assert.equal((await call('quotes/send-email',{output_token:output.output_token},guest)).status,200);
 assert.equal(sent.length,1);assert.equal(sent[0].to[0].email,quote.customer_email);assert.match(sent[0].textContent,/1,234/);
 failEmail=true;assert.equal((await call('quotes/send-email',{output_token:output.output_token},guest)).status,502);failEmail=false;
 assert.equal((await db.query("SELECT * FROM events WHERE event_type='quote_sent'")).rows.length,1,'failed delivery is not counted');
 const downloaded=await(await call('quotes/preview/export',{output_token:output.output_token},guest)).json();assert.equal(downloaded.total,1234);
 const other=(await(await call('guest/start',{browser_id:'other-anonymous-browser'})).json()).token;
 assert.equal((await call('quotes/send-email',{output_token:output.output_token},other)).status,403,'output belongs to its guest');
 assert.equal((await call('quotes/send-email',{output_token:output.output_token+'x'},guest)).status,400,'tampering rejected');
 for(const event_type of ['quote_started','save_prompt_shown','signup_screen_viewed','signup_attempted'])assert.equal((await call('events/funnel',{event_type},guest)).status,200);
 const admin=jwt.sign({admin:true},process.env.JWT_SECRET+'_admin');
 const funnel=await(await call('admin/funnel?period=today',null,admin,'GET')).json();
 assert.equal(funnel.anonymousFreeStarts,2);assert.equal(funnel.anonymousQuoteStarts,1);assert.equal(funnel.anonymousQuoteCompletions,13);assert.equal(funnel.anonymousQuoteSends,1);assert.equal(funnel.savePrompts,1);assert.equal(funnel.signupAttempts,1);
 // Register while active: original clock survives and exact quote is saved once.
 const reg=await call('auth/register',{name:'Test Tradesperson',email:'tester@example.invalid',password:'test-only-password',guest_token:guest,browser_id:'fresh-anonymous-browser'},null,'POST',cookie);assert.equal(reg.status,200);
 const account=await reg.json();
 const after=await(await call('auth/me',null,account.token,'GET')).json();assert.equal(after.trial_ends_at,before.trial_ends_at);
 assert.equal((await call('quotes/send-email',{output_token:output.output_token},guest)).status,401,'converted session revoked');
 const save=await(await call('quotes',{...quote,output_token:output.output_token},account.token)).json();const repeat=await(await call('quotes',quote,account.token)).json();assert.equal(save.id,repeat.id);
 const library=await(await call('quotes',null,account.token,'GET')).json();assert.equal(library.length,1);assert.equal(Number(library[0].total),1234);assert.deepEqual(library[0].quote_data,quote.quote_data);
 const afterSave=await(await call('admin/funnel?period=today',null,admin,'GET')).json();assert.equal(afterSave.quoteCompletions,13,'Save does not double-count anonymous completion');
 const otherId=jwt.verify(other,process.env.JWT_SECRET).id;
 await db.query("UPDATE quote_allowances SET trial_started_at=NOW()-INTERVAL '7 days' WHERE id=(SELECT trial_id FROM guest_sessions WHERE id=$1)",[otherId]);
 assert.equal((await call('quotes/preview',quote,other)).status,402,'expiry enforced by server');
 assert.equal((await call('quotes/send-email',{output_token:output.output_token},other)).status,402);
 const restarted=(await(await call('guest/start',{browser_id:'other-anonymous-browser'})).json()).token;
 assert.equal((await call('quotes/preview',quote,restarted)).status,402,'restart cannot reset trial');
 assert.equal((await db.query("SELECT * FROM events WHERE event_type='anonymous_free_use_started'")).rows.length,2,'start event recorded once per trial');
});
