const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const express=require('express');
const jwt=require('jsonwebtoken');
const https=require('node:https');
const {EventEmitter}=require('node:events');
const {PGlite}=require('@electric-sql/pglite');

test('guest signup transfers exact quote atomically, rejects reuse, and unlocks server email',async(t)=>{
  process.env.JWT_SECRET='conversion-test-secret';
  process.env.BREVO_API_KEY='test-not-a-real-key';
  delete process.env.GA_API_SECRET;
  const sent=[];
  const originalRequest=https.request;
  https.request=(options,callback)=>{
    const req=new EventEmitter(); let body='';
    req.write=chunk=>body+=chunk;
    req.end=()=>{sent.push(JSON.parse(body));const res=new EventEmitter();res.statusCode=201;callback(res);queueMicrotask(()=>res.emit('end'));};
    return req;
  };
  t.after(()=>{https.request=originalRequest;});
  const db=new PGlite();
  await db.exec(fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8'));
  let failTransfer=false;
  const query=(sql,args)=>{
    if(failTransfer&&sql.startsWith('UPDATE quotes SET user_id')) throw new Error('Simulated transfer failure');
    return db.query(sql,args);
  };
  const pool={query,connect:async()=>({query,release(){}})};
  const app=express();app.use(express.json());app.locals.pool=pool;
  app.use('/api/auth',require('../routes/auth'));app.use('/api/quotes',require('../routes/quotes'));
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  t.after(async()=>{await new Promise(r=>server.close(r));await db.close();});
  const base=`http://127.0.0.1:${server.address().port}`;
  const request=(url,body,token,method='POST')=>fetch(base+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const guestId='00000000-0000-4000-8000-000000000042';
  await db.query('INSERT INTO guest_sessions(id,browser_hash,ip_hash) VALUES($1,$2,$3)',[guestId,'browser42','ip42']);
  const guest=jwt.sign({id:guestId,guest:true},process.env.JWT_SECRET,{expiresIn:'1h'});
  const quote={customer_name:'Quote test',customer_email:'customer@example.invalid',job_description:'Complete rewire',days:6.5,day_rate:200,total:8698,profit_percent:30,quote_data:{pricingVersion:2,total:8698,profit:2610,profitPct:30,customer_email:'customer@example.invalid',scopeTasks:['Testing'],materials:3600,vatRate:0}};
  const created=await request('/api/quotes',quote,guest);assert.equal(created.status,200);
  const saved=await created.json();
  assert.equal((await request('/api/quotes/send-email',quote,guest)).status,403);
  assert.equal(sent.length,0);
  const registration={name:'Test Electrician',email:'electrician@example.invalid',password:'test-password',trade:'Electrician',guest_token:guest};
  failTransfer=true;
  assert.equal((await request('/api/auth/register',registration)).status,500);
  assert.equal((await db.query('SELECT * FROM users')).rows.length,0,'failed transfer rolls back account creation');
  assert.equal((await db.query('SELECT guest_id FROM quotes WHERE id=$1',[saved.id])).rows[0].guest_id,guestId);
  failTransfer=false;
  const response=await request('/api/auth/register',registration);assert.equal(response.status,200);
  const account=await response.json();
  const list=await (await request('/api/quotes',null,account.token,'GET')).json();
  assert.equal(list.length,1);assert.equal(list[0].id,saved.id);assert.equal(list[0].guest_id,null);
  assert.deepEqual(list[0].quote_data,quote.quote_data);assert.equal(Number(list[0].total),8698);
  assert.equal((await request('/api/auth/register',{...registration,email:'reuse@example.invalid'})).status,500);
  assert.equal((await db.query('SELECT * FROM users')).rows.length,1,'guest token cannot be converted twice');
  const emailResponse=await request('/api/quotes/send-email',{quote_id:saved.id},account.token);assert.equal(emailResponse.status,200);
  const delivered=sent.find(item=>item.subject.startsWith('Your quotation from'));
  assert.equal(delivered.sender.email,'hello@profitquote.co.uk');
  assert.equal(delivered.to[0].email,quote.customer_email);
  assert.doesNotMatch(JSON.stringify(delivered),/latepay/i);
  assert.equal((await request('/api/auth/register',{name:'Regular signup',email:'regular@example.invalid',password:'test-password'})).status,200);
});
