const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const express=require('express');
const jwt=require('jsonwebtoken');
const https=require('node:https');
const {EventEmitter}=require('node:events');
const {PGlite}=require('@electric-sql/pglite');

for (const billingPlan of [
  {name:'legacy £49',price:'price_1TZX0w8466uzy1MNeVvWz2Ew',link:'plink_1TZX128466uzy1MNZEoilqdL'},
  {name:'current £37',price:'price_1UHgUj8466uzy1MNcCnTWJbi',link:'plink_1UHgWz8466uzy1MNDtQyGajQ'}
]) test('three lifetime free quotes, signed billing and saved-only output — '+billingPlan.name,async(t)=>{
  process.env.JWT_SECRET='limits-test-only';process.env.STRIPE_WEBHOOK_SECRET='webhook-test-only';delete process.env.GA_API_SECRET;
  const original=https.request;const sent=[];
  https.request=(options,cb)=>{const r=new EventEmitter();let body='';r.write=x=>body+=x;r.end=()=>{sent.push(JSON.parse(body));const res=new EventEmitter();res.statusCode=201;cb(res);queueMicrotask(()=>res.emit('end'));};return r;};
  t.after(()=>{https.request=original;});
  const db=new PGlite();const schema=fs.readFileSync(path.join(__dirname,'../schema.sql'),'utf8');await db.exec(schema);
  let queue=Promise.resolve();
  const pool={query:db.query.bind(db),connect:async()=>{const previous=queue;let release;queue=new Promise(r=>release=r);await previous;return {query:db.query.bind(db),release};}};
  const app=express();app.locals.pool=pool;
  const billing=require('../routes/billing');
  app.post('/api/billing/webhook',express.raw({type:'application/json'}),billing.webhook);
  app.use(express.json());app.use('/api/billing',billing.router);app.use('/api/auth',require('../routes/auth'));app.use('/api/guest',require('../routes/guest'));app.use('/api/quotes',require('../routes/quotes'));
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  t.after(async()=>{await new Promise(r=>server.close(r));await db.close();});
  const base=`http://127.0.0.1:${server.address().port}`;
  const request=(url,body,token,cookie,method='POST')=>fetch(base+url,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const quote=()=>({customer_name:'Test customer',customer_email:'customer@example.invalid',job_description:'Rewire',total:8698,days:6.5,quote_data:{customer_email:'customer@example.invalid',total:8698,profit:2610},creation_key:crypto.randomUUID()});
  const browser='browser-for-limit-tests';
  const guestResponse=await request('/api/guest/start',{browser_id:browser});assert.equal(guestResponse.status,200);
  const cookie=guestResponse.headers.get('set-cookie').split(';')[0];const guest=(await guestResponse.json()).token;
  const firstBody=quote();const first=await (await request('/api/quotes',firstBody,guest,cookie)).json();assert.equal(first.quotes_remaining,2);
  const duplicate=await (await request('/api/quotes',firstBody,guest,cookie)).json();assert.equal(duplicate.id,first.id);assert.equal(duplicate.quotes_remaining,2);
  const reg=await request('/api/auth/register',{name:'User one',email:'first@example.invalid',password:'test-password',guest_token:guest,browser_id:browser},null,cookie);assert.equal(reg.status,200);
  const account=await reg.json();const token=account.token;
  const me=await (await request('/api/auth/me',null,token,cookie,'GET')).json();assert.equal(me.quotes_remaining,2,'signup must not reset guest use');
  assert.equal((await request('/api/quotes',quote(),guest,cookie)).status,401,'converted guest token revoked');
  const second=await (await request('/api/quotes',quote(),token,cookie)).json();assert.equal(second.quotes_remaining,1);
  const race=await Promise.all([request('/api/quotes',quote(),token,cookie),request('/api/quotes',quote(),token,cookie)]);
  assert.deepEqual(race.map(r=>r.status).sort(),[200,402]);
  await request('/api/quotes/'+second.id,null,token,cookie,'DELETE');
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,402,'deletion does not refund credits');
  await db.exec(schema);
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,402,'migration/restart does not reset counters');
  const repeat=await request('/api/auth/register',{name:'Repeat',email:'repeat@example.invalid',password:'test-password',browser_id:'different-browser-id'},null,cookie);
  assert.equal(repeat.status,200);const repeatToken=(await repeat.json()).token;
  assert.equal((await request('/api/quotes',quote(),repeatToken,cookie)).status,402,'signed cookie shares allowance across accounts');
  const other=await request('/api/auth/register',{name:'Other person',email:'other@example.invalid',password:'test-password',browser_id:'genuinely-other-browser'});
  assert.equal(other.status,200);const otherToken=(await other.json()).token;
  assert.equal((await request('/api/quotes',quote(),otherToken)).status,200,'shared network alone does not share quote allowance');
  assert.equal((await request('/api/quotes/send-email',quote(),token,cookie)).status,404,'raw quote body cannot bypass counter');
  assert.equal((await request('/api/quotes/send-email',{quote_id:first.id},otherToken)).status,404,'other account cannot send the quote');
  assert.equal((await request('/api/quotes/'+first.id+'/export',null,otherToken,null,'GET')).status,404);
  assert.equal((await request('/api/quotes/'+first.id+'/export',null,token,cookie,'GET')).status,200,'existing output remains available');
  process.env.BREVO_API_KEY='test';
  assert.equal((await request('/api/quotes/send-email',{quote_id:first.id,total:1,customer_email:'wrong@example.invalid'},token,cookie)).status,200);
  assert.equal(sent.at(-1).to[0].email,'customer@example.invalid');assert.match(sent.at(-1).textContent,/8,698/);
  const checkout=await (await request('/api/billing/checkout',{},token,cookie)).json();
  assert.equal(new URL(checkout.url).pathname,'/14AcMZf5F4L453h8MQc3m0x','new checkouts use the £37 payment link');
  const reference=new URL(checkout.url).searchParams.get('client_reference_id');assert.ok(reference);
  const now=Math.floor(Date.now()/1000);let sequence=0;
  const postEvent=async(type,object,created=now,signature=true)=>{
    const raw=JSON.stringify({id:'evt_test_'+(++sequence),livemode:true,created,type,data:{object}});
    const signatureValue=crypto.createHmac('sha256',process.env.STRIPE_WEBHOOK_SECRET).update(now+'.'+raw).digest('hex');
    return fetch(base+'/api/billing/webhook',{method:'POST',headers:{'Content-Type':'application/json','stripe-signature':`t=${now},v1=${signature?signatureValue:'0'.repeat(64)}`},body:raw});
  };
  const sub={id:'sub_test_pq',customer:'cus_test',status:'active',items:{data:[{price:{id:billingPlan.price},current_period_end:now+86400}]}};
  assert.equal((await postEvent('customer.subscription.created',sub,now,false)).status,400);
  assert.equal((await postEvent('customer.subscription.created',{...sub,status:'incomplete'})).status,200);
  await postEvent('customer.subscription.updated',sub);
  await postEvent('customer.subscription.created',{...sub,status:'incomplete'});
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,402,'subscription not bound to a paid checkout yet');
  const session={subscription:sub.id,customer:sub.customer,payment_link:billingPlan.link,mode:'subscription',payment_status:'paid',client_reference_id:reference};
  assert.equal((await postEvent('checkout.session.completed',{...session,payment_link:'unrelated_link'})).status,200);
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,402);
  assert.equal((await postEvent('checkout.session.completed',session)).status,200);
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,200,'paid subscriber can create quote four');
  await postEvent('customer.subscription.updated',{...sub,cancel_at_period_end:true},now+1);
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,200,'scheduled cancellation keeps paid period access');
  await postEvent('customer.subscription.deleted',{...sub,status:'canceled'},now+2);
  await postEvent('customer.subscription.updated',sub,now);
  assert.equal((await request('/api/quotes',quote(),token,cookie)).status,402,'late events cannot restore canceled access');
  const updated=await (await request('/api/billing/status',null,token,cookie,'GET')).json();assert.equal(updated.subscribed,false);
  await request('/api/auth/register',{name:'Fourth',email:'fourth@example.invalid',password:'test-password'});
  await request('/api/auth/register',{name:'Fifth',email:'fifth@example.invalid',password:'test-password'});
  assert.equal((await request('/api/auth/register',{name:'Sixth',email:'sixth@example.invalid',password:'test-password'})).status,429,'account farming throttled');
});
